server:
  port: 8080
spring:
  application:
    name: MediTrack
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: meditrack
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://127.0.0.1:5432/postgres
